Bg/intake commands
StuyPulse/Dorcas pull request #12
Opened 2022-02-02 21:45 UTC by BenG49

Create Intake commands:

- IntakeAcquireCommand
- IntakeAcquireForeverCommand
- IntakeDeacquireCommand
- IntakeDeacquireForeverCommand
- IntakeExtendCommand
- IntakeRetractCommand

![image](https://user-images.githubusercontent.com/64862590/152242396-5ad900cb-20ae-450a-ba82-cbe20a4c8b38.png)
![image](https://user-images.githubusercontent.com/64862590/152242473-f0d28932-c4c7-4864-adb0-cc7d5508f3ef.png)

2022-02-03 03:22 UTC, selym3 commented
Fantastic pull request. Good work!

2022-02-03 05:56 UTC, Sam-Belliveau requested changes

2022-02-03 05:56 UTC, Sam-Belliveau commented on src/main/java/com/stuypulse/robot/commands/intake/IntakeAcquireForeverCommand.java
> +	public void execute() {
this should be initialize

2022-02-03 05:56 UTC, Sam-Belliveau commented on src/main/java/com/stuypulse/robot/commands/intake/IntakeExtendCommand.java
> +	public void execute() {
this should be initialize

2022-02-03 05:57 UTC, selym3 commented on src/main/java/com/stuypulse/robot/commands/intake/IntakeExtendCommand.java
> +	public void execute() {
agreed

2022-02-03 05:57 UTC, selym3 commented on src/main/java/com/stuypulse/robot/commands/intake/IntakeAcquireForeverCommand.java
> +	public void execute() {
^^^^

2022-02-03 05:58 UTC, selym3 commented on src/main/java/com/stuypulse/robot/commands/intake/IntakeRetractCommand.java
> +		intake.retract();
initialize

2022-02-04 22:06 UTC, Sam-Belliveau approved these changes

2022-02-04 22:06 UTC, merged