Create Shooter Subsystem
StuyPulse/Dorcas pull request #7
Opened 2022-01-26 21:27 UTC by nlin21

2022-01-26 21:56 UTC, Sam-Belliveau requested changes

2022-01-26 21:56 UTC, Sam-Belliveau commented on src/main/java/com/stuypulse/robot/Constants.java
> +                double RING_SETPOINT = 3900.0;
these should be `SmartNumber`'s

2022-01-26 21:56 UTC, Sam-Belliveau commented on src/main/java/com/stuypulse/robot/subsystems/Shooter.java
> +    private double FEEDER_FF = 0.0;
All of these should be in `Constants` and should all be `SmartNumber`'s

2022-01-26 21:56 UTC, Sam-Belliveau commented on src/main/java/com/stuypulse/robot/subsystems/Shooter.java
> +        feederMotor = new CANSparkMax(-1, MotorType.kBrushless);
All of these should be in `Constants.Ports`

2022-01-26 21:56 UTC, Sam-Belliveau commented on src/main/java/com/stuypulse/robot/subsystems/Shooter.java
> +        SmartDashboard.putNumber("Feeder F value" , FEEDER_FF);
These can be removed when we convert to `SmartNumber`

2022-01-26 21:56 UTC, Sam-Belliveau commented on src/main/java/com/stuypulse/robot/subsystems/Shooter.java
> +        feeder_F = SmartDashboard.getNumber("Feeder F value" , FEEDER_FF);
This can be replaced with `SmartNumber.get`

2022-01-26 21:56 UTC, Sam-Belliveau commented on src/main/java/com/stuypulse/robot/subsystems/Shooter.java
> +        if((shooter_D != FEEDER_D)) { shooterPIDController.setP(shooter_D); FEEDER_FF = shooter_F; }
There are many typos in this block of code.

- You repeat D multiple times
- you only ever set Shooter P
- You don't actually change feeder values
- You change constant values

2022-01-26 21:56 UTC, Sam-Belliveau commented on src/main/java/com/stuypulse/robot/subsystems/Shooter.java
> +        shooterPIDController.setReference(FIELD.RING_SETPOINT, CANSparkMax.ControlType.kVelocity);
This RPM value should be a member variable that can be changed with functions

2022-01-27 03:15 UTC, selym3 commented
Looking snazzy

2022-01-28 22:41 UTC, Sam-Belliveau approved these changes
Good Job!

2022-01-28 22:41 UTC, merged